name: CI/CD Pipeline for Juice Shop

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull bkimminich/juice-shop

      - name: Run Juice Shop
        run: docker run -d -p 3000:3000 bkimminich/juice-shop

#CodeQL Analysis 

  codeql:
    name: Static Application Security Testing (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript  

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2



#DAST with OWASP ZAP
  owasp-zap:
    name: Dynamic Application Security Testing (DAST)
    runs-on: ubuntu-latest
    steps:
      - name: Start Juice Shop (Docker)
        run: docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Run OWASP ZAP
        run: |
          docker run -v $(pwd):/zap/wrk -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000 -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
